exports.LEAST_MATCHES_REQUIRED = 3;
exports.REQUIRED_MATCHES_FOR_MAGIC = 3;

exports.BOARD_WIDTH = 455;
exports.BOARD_HEIGHT = 455;

exports.TOUCH_MOVE_THRESHOLD_FOR_SWAP_GEM = 25;
exports.HINT_POTENTIAL_MATCH_TIME = 2000;

exports.GEM_TYPE_MAGIC = 6;

exports.GRAVITY_FALL = 0;
exports.FLIP_OUT = 1;
