exports.LEAST_MATCHES_REQUIRED = 3;
exports.REQUIRED_MATCHES_FOR_MAGIC = 5;

exports.BOARD_WIDTH = 455;
exports.BOARD_HEIGHT = 455;

exports.TOUCH_MOVE_THRESHOLD_FOR_SWAP_GEM = 25;
exports.HINT_POTENTIAL_MATCH_TIME = 2000;

exports.GEM_TYPE_MAGIC = 6;
exports.GEM_TYPE_COUNT = 7;

exports.GRAVITY_FALL = 0;
exports.FLIP_OUT = 1;

exports.ENEMY_ADD_COINS_TIME = 1500;
exports.SPAWN_INTERVAL = 1000;
exports.PLAYER_MAX_HP = 100.0;